### ISSUE TITLE
I want to contribute with 3D models

### ISSUE THREAD

**Issue by michaelizer** [robinstechprojects/CubeRoad#2]
Greetings,

I come from Utopian.io, a community that rewards contributions to open source projects like yours. I could help with whatever your need, I'll get rewarded for it and you will get a helping hand with the models of you game. Just tell me if you are interested, if yes then what do you want me to start with?

**Comment by robinstechprojects** [comment]
Wow, thanks ! 

Surely i´m interested in your help. I´ll reach out to you when i reach a Point where your support could become handy. 

Regards

**Comment by robinstechprojects** [comment]
I just invited you as collabortor to this repository, so that you can start right away if needed.

**Comment by michaelizer** [comment]
Invitation accepted, I'll be waiting for your demands :)

**Comment by robinstechprojects** [comment]
Nice, thank you very very much.
